// export enum Domain {
//   UPDATE_DOMAIN_DATA = 'UPDATE_DOMAIN_DATA',
//   UPDATE_CURRENT_DOMAIN = 'UPDATE_CURRENT_DOMAIN',
// }

export const Domain = {
  UPDATE_DOMAIN_DATA: 'UPDATE_DOMAIN_DATA',
  UPDATE_CURRENT_DOMAIN: 'UPDATE_CURRENT_DOMAIN',
};
