{
 "title": "TCC监控仪表盘",
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "实例",
    "query": {
     "query": "label_values(TCC_SERVER_SUCCESS_RPC_REQUEST_NUMS_total,Instance)"
    }
   },
   {
    "name": "serviceCode",
    "label": "请求方法",
    "query": {
     "query": "label_values(TCC_SERVER_SUCCESS_RPC_REQUEST_NUMS_total,ServiceCode)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "请求QPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "((sum(rate(TCC_SERVER_SUCCESS_RPC_REQUEST_NUMS_total{Instance=~\"$instance\",ServiceCode=~\"$serviceCode\"}[2m])) by ()) or on() vector(0))\n+ ((sum(rate(TCC_SERVER_FAIL_RPC_REQUEST_NUMS_total{Instance=~\"$instance\",ServiceCode=~\"$serviceCode\"}[2m])) by ()) or on() vector(0))",
     "legendFormat": "QPS"
    }
   ]
  },
  {
   "title": "请求耗时",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "(sum(rate(TCC_SERVER_RPC_REQUEST_COSTS_DISTRIBUTION_count{Instance=~\"$instance\",ServiceCode=~\"$serviceCode\"}[2m])) by (Instance,ServiceCode)) /\n((sum(rate(TCC_SERVER_RPC_REQUEST_COSTS_DISTRIBUTION_sum{Instance=~\"$instance\",ServiceCode=~\"$serviceCode\"}[2m])) by (Instance,ServiceCode)) )",
     "legendFormat": "{{Instance}}-{{ServiceCode}} avg"
    },
    {
     "expr": "histogram_quantile(0.9, rate(TCC_SERVER_RPC_REQUEST_COSTS_DISTRIBUTION_bucket{Instance=~\"$instance\",ServiceCode=~\"$serviceCode\"}[2m]) )",
     "legendFormat": "{{Instance}}-{{ServiceCode}} 90"
    },
    {
     "expr": "histogram_quantile(0.99, rate(TCC_SERVER_RPC_REQUEST_COSTS_DISTRIBUTION_bucket{Instance=~\"$instance\",ServiceCode=~\"$serviceCode\"}[2m]) )",
     "legendFormat": "{{Instance}}-{{ServiceCode}} 99"
    },
    {
     "expr": "histogram_quantile(1, rate(TCC_SERVER_RPC_REQUEST_COSTS_DISTRIBUTION_bucket{Instance=~\"$instance\",ServiceCode=~\"$serviceCode\"}[2m]) )",
     "legendFormat": "{{Instance}}-{{ServiceCode}} max"
    }
   ]
  },
  {
   "title": "请求成功率",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "%" } },
   "targets": [
    {
     "expr": "100*(sum(rate(TCC_SERVER_SUCCESS_RPC_REQUEST_NUMS_total{Instance=~\"$instance\",ServiceCode=~\"$serviceCode\"}[2m])) by () or on() vector(0)) /\n((sum(rate(TCC_SERVER_SUCCESS_RPC_REQUEST_NUMS_total{Instance=~\"$instance\",ServiceCode=~\"$serviceCode\"}[2m])) by () or on() vector(0)) + ((sum(rate(TCC_SERVER_FAIL_RPC_REQUEST_NUMS_total{Instance=~\"$instance\",ServiceCode=~\"$serviceCode\"}[2m])) by () or on() vector(0))))",
     "legendFormat": "成功率"
    }
   ]
  }
 ]
}